# Generated by Django 4.2.6 on 2023-10-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=100)),
                ('anime_genre', models.CharField(max_length=50)),
                ('car_imdb_rate', models.IntegerField()),
            ],
        ),
    ]
