# Generated by Django 4.2.6 on 2023-10-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animes',
            old_name='car_imdb_rate',
            new_name='anime_imdb_rate',
        ),
    ]
